import type {OsomTheme} from './interface';

export const DEFAULT_DARK_THEME = {
  fontSans: '',
  fontSerif: '',
  fontMono: '',
  colorBase100: '',
  colorBase200: '',
  colorBase300: '',
  colorBaseContent: '',
  colorPrimary: '',
  colorPrimaryContent: '',
  colorSecondary: '',
  colorSecondaryContent: '',
  colorInfo: '',
  colorInfoContent: '',
  colorSuccess: '',
  colorSuccessContent: '',
  colorWarning: '',
  colorWarningContent: '',
  colorError: '',
  colorErrorContent: '',
  sizeCell: '',
  roundedBox: '',
  roundedBtn: '',
  roundedBadge: '',
} as OsomTheme;
