import type {OsomTheme} from './interface';

export const DEFAULT_LIGHT_THEME = {
  colorScheme: 'light',
  fontSans: 'Noto Sans KR',
  fontSerif: 'Hahmlet Variable',
  fontMono: 'Nanum Gothic Coding',
  colorBase100: '#faf7f5',
  colorBase200: '#efeae6',
  colorBase300: '#e7e2df',
  colorBaseContent: '#291334',
  colorPrimary: '#65c3c8',
  colorPrimaryContent: '#d4dbff',
  colorSecondary: '#ef9fbc',
  colorSecondaryContent: '#fff9fc',
  colorAccent: '#eeaf3a',
  colorAccentContent: '#00100d',
  colorNeutral: '#291334',
  colorNeutralContent: '#d7dde4',
  colorInfo: '#00b3f0',
  colorInfoContent: '#000000',
  colorSuccess: '#00ca92',
  colorSuccessContent: '#000000',
  colorWarning: '#ffc22d',
  colorWarningContent: '#000000',
  colorError: '#ff6f70',
  colorErrorContent: '#000000',
  sizeCell: '3rem',
  roundedBox: '0.75rem',
  roundedBtn: '0.5rem',
  roundedBadge: '0.25rem',
} as OsomTheme;
